### ISSUE TITLE
Testing the checker

### ISSUE THREAD

**Issue by 0xSEC** [comicrelief/grants-eligibility-form#20]
- To test the logic: We need to test that the checker follows the correct logic as per the initial flow diagram here: https://drive.google.com/file/d/1p5DIo1Hzmwt2g1X7pT-8MQL3NgfmwVxE/view?usp=sharing

- To test the FE

- To test in-situ

**Comment by AndyEPhipps** [comment]
Link to test here, bottom of the page: https://staging.comicrelief.com/funding/applying-for-grants/open-initiatives

A few other notes: images are currently placeholders being hosted elsewhere, so there's a small delay in them loading upon a successful submission

There's an issue with the endpoint URL not being passed to the Netlify env properly, but this only affects submission in the back, there's no difference within the form experience itself

**Comment by k-pammi** [comment]
@0xSEC, @AndyEPhipps
QUESTION 7 - ‘Sport for change’
Scenario 2: `If User clicks on ‘No’ and clicked on ‘No’ for QUESTION 5 return MESSAGE 6 ‘We don’t think you’re eligible’ which displays LT and SSS initiatives with the reason as ‘sport related change only`
https://docs.google.com/document/d/1cvgl_Yj2sAvyO6Ydsg4ij6FEqEoywhGVx9iK3w3kM0o/edit

Given I am on Question 7, 
And I clicked on 'No' for QUESTION 5
And I clicked on 'No' for QUESTION 6
When I clicked on 'No' for QUESTION 7
Then I see 3 initiatives being displayed (LT, SSS, and CS with message of  ‘turnover less than £100k') instead of 2 initiatives that should display LT and SSS initiatives with the reason as ‘sport related change only` as mentioned in the scenario

Note: in the above scenario it's not mentioned what user clicks for QUESTION 6, so i clicked on 'No'

**Comment by 0xSEC** [comment]
In this scenario, the user does not want core costs so shouldn't be shown that they're ineligible for it as they didn't want it. @AndyEPhipps  we need to remove that row and only leave in LT and SSS.

**Comment by k-pammi** [comment]
Issues on browsers: 
1. On WIn 7 IE11, 
Question 7 - `No` button is not clickable, 
Question 8 - `India, South Africa, Brazil Or Kenya` and `Somewhere else` buttons are not clickable
Question 9 - `yes` and `No` buttons are not clickable

**Comment by AndyEPhipps** [comment]
Odd, I'm not having any trouble at all clicking those buttons using Browserstack, W7 IE11; there's nothing different about those specific questions that would react differently. Was this in BS or on your own machine, @k-pammi ?

**Comment by k-pammi** [comment]
@AndyEPhipps as dicussed, below are the steps for the blank page issue
1. Given I clicked 'Yes' on Question 5
2. And I clicked 'Yes' on Question 6
3.  And I clicked 'No' on Question 7 then it showed all 3 initiatives that i'm not eligible, So I clicked on back button and clicked 'Yes' on Question 7
4. And I clicked on 'India, South Africa, Brazil Or Kenya' button 
5. Then I see the pop up alert error
 
![image](https://user-images.githubusercontent.com/16117926/38248518-8781b6a2-3740-11e8-91f9-2f4c2c9b9c16.png)

6. When I click 'Ok' on the pop up window
7. Then I see a 'Blank page'
![image](https://user-images.githubusercontent.com/16117926/38248542-9d7591cc-3740-11e8-970c-ce29265a7632.png)

Note: This is on my native Chrome browser v65 on ubuntu

**Comment by k-pammi** [comment]
@AndyEPhipps **Issue 3** is fixed

**Comment by AndyEPhipps** [comment]
Just for visibility, it seems like all of those errors (which were triggering the alert popup I put in) were due to browser 'back' and 'forward'-ing through the form, resetting variables that are required.

As such, on @0xSEC and Grants' guidance, we're now resetting the form if a user clicks Back while on a rejection/success message, so they'll be taken to the intro page of the form.

I'd expect this to take care of those issues, and it also stops users from mis-using the form.

**Comment by k-pammi** [comment]
**Issue 2** is fixed

**Comment by AndyEPhipps** [comment]
@k-pammi  I've just done a quick check on the mentioned iPhone X button problem (on Browserstack), and everything seems to be working fine for me. Can you confirm this? I've also tried on my own iPhone 6S and a few others, and all seems well.

I think most/all of the 'thing not working' style issues were down to that 'back browser' bug, I'm hoping they're not all taken care of with that 'reset' functionality.

The weird 'continue' button on the organisation name question is just a style thing, as it looks like iOS is using a native-ish button there, can address this in v2 I think.

Have made a few minor updates to the message copy, an incorrect row was being shown on message; @0xSEC has confirmed that all message copy is now right, so if there's any documents contradiction the app build, we might need to raise it with Grants/UX.

**Comment by 0xSEC** [comment]
Thanks @AndyEPhipps, we can update the user flow to show correct messaging but I confirmed with Laura and Adam re the messaging this morning that I then confirmed with you.

**Comment by 0xSEC** [comment]
We have had to add another initiative into the checker and therefore the logic needs retesting. The test notes have been updated and are here: https://docs.google.com/document/d/1O7Iebe3lhif83HPSH286ALM3paqr-750i97pGJ0Dbc0/edit?usp=sharing

The logic has been updated and is here: https://drive.google.com/file/d/1UmaXjmfdpzOb3ESpfBDDcNFwcVM3crrj/view?usp=sharing

**Comment by k-pammi** [comment]
Above issue is fixed
